### ISSUE TITLE
Refactor: Hook add favorites logic into new client

### ISSUE THREAD

**Issue by Thompson632** [torieee/WSIE#150]
# Tasks
- [x] Allow user to add recipes to favorites when logged in
- [x] Show error to user when not logged in
- [x] Remove recipe from user favorites
