### ISSUE TITLE
Feature: Build user profile page

### ISSUE THREAD

**Issue by Thompson632** [torieee/WSIE#151]
# Tasks
- [x] Display user profile info
- [x] Allow user to update first name and last name
- [x] Allow user to update password
- [x] Allow user to update email
