### ISSUE TITLE
Refactor: Hook in dietary updates to new client

### ISSUE THREAD

**Issue by Thompson632** [torieee/WSIE#152]
# Tasks
- [x] Add/update dietary restrictions 
- [x] Show success/failure to user
- [x] Add/update food allergies
- [x] Show success/failure to user
